; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool on Tue Feb 27 2018 20:56:15 GMT+0000 (GMT Standard Time)
; Wait for set temperatures to be reached

M116 P1 ; wait for tool 0 only to reach operating temperature
M83 ; relative extruder mode
G1 E2 F2500 ; undo retraction